name: mott
channels:
- defaults
- pytorch
dependencies:
- python=3.7
- pip
- numpy
- jupyter
- matplotlib
- scikit-learn
- scipy
- pandas
- seaborn
- nltk
- h5py
- spacy
- unidecode
- pytorch>=1.7.0
- torchvision=0.4.0
- cudatoolkit=10.0
- pip:
  - pyyaml
  

